#!  /bin/bash

selfDir=$(dirname $0)
BINARY="$selfDir/bin"
objDir="$selfDir/obj"

find "${objDir}" -maxdepth 1 -not -wholename "${objDir}" -exec rm -rv {} \;
if [ -f "$BINARY" ] ; then 
    rm -v "$BINARY"
fi


exit 0
