#!  /bin/bash

selfDir=$(dirname $0)

echo "Make log"
echo "========"
$selfDir/clean
$selfDir/debug
echo "========"
if [ -f "$selfDir/bin" ]; then 
    echo "$selfDir/bin"
    $selfDir/bin
fi

exit 0
